<template>
  <FadeInUp>
    <div class="relative">
      <UPageCard
        variant="subtle"
        class="rounded-2xl"
      >
        <video
          class="rounded-xl"
          data-v-baf90ddd=""
          preload="none"
          poster="/images/reel.png"
          :controls="true"
        >
          <source
            data-v-baf90ddd=""
            src="https://player.vimeo.com/progressive_redirect/playback/863697186/rendition/1080p/file.mp4?loc=external&log_user=0&signature=ace347a7ef2ae2c91e3efd8640f53115e73bdc49bb08c3e708613f404465b9d4"
            type="video/mp4"
          >
        </video>
      </UPageCard>
    </div>
  </FadeInUp>
</template>
